#define L_MOTOR_DIRECTION 13
#define BOTH_MOTORS_PWM 11
#define R_MOTOR_DIRECTION 9

#define PRESS_SERVO_PWM 10
#define TRAPDOOR_SERVO_PWM 5

#define COLOR_OUTPUT1 7
#define COLOR_OUTPUT2 2
#define COLOR_INPUT A0

#define ULTRASONIC_TRIGGER 3
#define ULTRASONIC_ECHO A1

#define INPUT_PINS[] {COLOR_INPUT,ULTRASONIC_ECHO}
#define OUTPUT_PINS[] {L_MOTOR_DIRECTION,BOTH_MOTORS_PWM,R_MOTOR_DIRECTION,PRESS_SERVO_PWM,\
                        TRAPDOOR_SERVO_PWM,COLOR_OUTPUT1,COLOR_OUTPUT2}
